// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace StockPricePredictionML.Model
{
    public class ModelInput
    {
        [ColumnName("date"), LoadColumn(0)]
        public string Date { get; set; }


        [ColumnName("symbol"), LoadColumn(1)]
        public string Symbol { get; set; }


        [ColumnName("open"), LoadColumn(2)]
        public float Open { get; set; }


        [ColumnName("close"), LoadColumn(3)]
        public float Close { get; set; }


        [ColumnName("low"), LoadColumn(4)]
        public float Low { get; set; }


        [ColumnName("high"), LoadColumn(5)]
        public float High { get; set; }


        [ColumnName("volume"), LoadColumn(6)]
        public float Volume { get; set; }


    }
}
